theme: jekyll-theme-cayman

title: "Reactor (Android library)"
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/docs/"
    id: "docs"
    subnav:
      - title: "Library"
        children:
          - title: "Quick Start"
            url: "/docs/library/quick-start.html"
          - title: "Example"
            url: "/docs/library/example.html"
          - title: "Use in an existing app"
            url: "/docs/library/existing-app.html"
      - title: "Architecture"
        children:
          - title: "Overview"
            url: "/docs/architecture/overview.html"
          - title: "Patterns"
            url: "/docs/architecture/patterns.html"
      - title: "Core"
        children:
          - title: "ReactorView"
            url: "/docs/core/reactor-view.html"
          - title: "ReactorTranslator"
            url: "/docs/core/reactor-translator.html"
      - title: "Extras"
        children:
          - title: "SharedPreferences"
            url: "/docs/extras/sharedpreferences.html"
          - title: "RecyclerView Adapter"
            url: "/docs/extras/recyclerview.html"
  - title: "About"
    url: "/about.html"
  - title: "Changelog"
    url: "https://github.com/filipproch/reactor-android/releases"
  - title: "Get library"
    url: "/index.html#add-library-to-your-project"