theme: jekyll-theme-cayman

title: "Reactor (Android library)"
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/docs/"
    id: "docs"
    subnav:
      - title: "Architecture"
        children:
          - title: "Overview"
            url: "/docs/architecture/overview.html"
          - title: "Patterns"
            url: "/docs/architecture/patterns.html"
          - title: "Example (simple)"
            url: "/docs/architecture/example-simple.html"
      - title: "Core"
        children:
          - title: "Views"
            url: "/docs/core/views.html"
          - title: "Events"
            url: "/docs/core/events.html"
          - title: "BaseTranslator"
            url: "/docs/core/base-translator.html"
      - title: "Extras"
        children:
          - title: "Views"
            url: "/docs/extras/views.html"
          - title: "SharedPreferences"
            url: "/docs/extras/sharedpreferences.html"
          - title: "RecyclerView Adapter"
            url: "/docs/extras/recyclerview.html"
  - title: "About"
    url: "/about.html"
  - title: "Get library"
    url: "/index.html#add-library-to-your-project"